the-complete-ruby-on-rails-developer-course/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :articles

  # This method is provided by the bcrypt gem.
  # It will hash the password and store it in the password_digest field.
  # See https://api.rubyonrails.org/v7.1.3.2/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password
  has_secure_password

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  # `self` refers to the instance of the class.
  before_save { self.email = email.downcase }
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # Set the article before the show, edit, update and destroy actions
  before_action :set_article, only: %i[show edit update destroy]

  def index
    # @articles = Article.all

    # use an explicit "per page" limit:
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    # No need to find the article because the before_action does it
    # @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    # No need to find the article because the before_action does it
    # @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @article
    else
      # Renders the new page with the form and the errors
      # The status code is 422 which means unprocessable entity
      # In Rails 7 you must pass the status: :unprocessable_entity option
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    # No need to find the article because the before_action does it
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully.'
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # No need to find the article because the before_action does it
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = 'Article was deleted successfully.'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      # flash.now is used to display flash messages on the same page.
      # See also https://guides.rubyonrails.org/action_controller_overview.html#flash-now
      flash.now[:alert] = 'There was something wrong with your login details'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def index
    # @users = User.all

    # use an explicit "per page" limit:
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    # @articles = @user.articles
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated'
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def signup; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Welcome to the Alpha Blog! You have successfully signed up.'
      redirect_to articles_path
    else
      # Renders the new page with the form and the errors
      # The status code is 422 which means unprocessable entity
      # In Rails 7 you must pass the status: :unprocessable_entity option
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/helpers/pages_helper.rb
module PagesHelper
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/helpers/users_helper.rb
module UsersHelper
  # This method will return the Gravatar for the given user.
  # it will be used in the users/show.html.erb file.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded mx-auto d-block')
  end
end

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user) %>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row justify-content-center offset-2">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3 text-center">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%# Instead of using the below form, this uses the partial template. %>
<%# It refers to 'form' because it's located in the same directory. %>
<%= render 'form' %>
<!--
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
-->

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<%# Top pagination %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%# Render article list partial %>
<%= render 'article' %>
<%# Bottom pagination %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>
<%# Without stye %>
<!--
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan=3>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'Create new article', new_article_path %>
</p>
-->

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%# Instead of using the below form, this uses the partial template. %>
<%# It refers to 'form' because it's located in the same directory. %>
<%= render 'form' %>
<!--
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
-->

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-body-tertiary" id="sticky-footer">
  <div class="container text-center">
    <span class="text-body-secondary text-white">Copy Right &copy; <%= link_to "My Website", "https://google.com" %></span>
  </div>
</footer>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  <% end %>
</div>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" id="navbar" aria-label="Eleventh navbar example">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample09">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Articles</a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Articles", articles_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, class: "nav-link", method: :delete %>
        </li>
      </ul>
      <form role="search">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>
    </div>
  </div>
</nav>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%# This will render the message from 'layouts/_messages.html.erb'(it's called partial template). %>
      <%# Check more about the partial template: https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/pages/about.html.erb
<h1>About page</h1>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="p-5 mb-4 bg-body-tertiary rounded-3" id="home-banner">
      <div class="container-fluid py-5 text-center text-white">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
      </div>
    </div>
  </div>
</div>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>
        <div class="form-group row justify-content-center offset-2">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Blogers</h1>
<%# Pagination %>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>
<% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to user.username, user %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %>
          </h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to "View profile", user, class: "btn btn-outline-success" %>
          <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %></small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%# Pagination %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup for Alpha Blog</h1>
<%= render 'form' %>

the-complete-ruby-on-rails-developer-course/alpha-blog/app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<%# gravartar_for method has been definded in the app/helpers/users_helper.rb. %>
<%= gravatar_for @user, size: 200 %>
<div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>
<h3 class="text-center mt-4">Articles</h3>
<%# Pagination %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%# Since _article.html.erb partial is located in different path. %>
<%# So you have to specify the path name in the prefix to refer to app/view/articles/_article.htnl.erb. %>
<%= render 'articles/article' %>
<%# Pagination %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>